module.exports = {
    env: {
        browser: true,
        es2021: true,
        node: true,
    },
    extends: ['eslint:recommended', 'plugin:@typescript-eslint/recommended'],
    overrides: [],
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
    },
    plugins: ['@typescript-eslint'],
    rules: {
        '@typescript-eslint/no-empty-function': 'off',
        'arrow-spacing': 'error',
        'indent': ['error', 4],
        'keyword-spacing': ['error'],
        'linebreak-style': ['error', 'unix'],
        'no-mixed-spaces-and-tabs': 'warn',
        'no-multiple-empty-lines': ['error', { 'max': 2, 'maxEOF': 1 }],
        'no-whitespace-before-property': 'error',
        'nonblock-statement-body-position': 'error',
        'no-confusing-arrow': 'error',
        'no-duplicate-imports': 'error',
        'no-empty-function': 'off',
        'no-var': 'error',
        'object-curly-spacing': ['error', 'always'],
        'object-shorthand': 'off',
        'prefer-const': 'error',
        'prefer-template': 'warn',
        quotes: ['error', 'single'],
        'space-before-blocks': 'error',
        'space-in-parens': 'error',
        'space-infix-ops': 'error',
        'space-unary-ops': 'error', 
        semi: ['error', 'never'],
    },
}